with player_games as (
    
    select * from {{ source('rocket_league', 'games_by_players') }}
),

players as (

    select
        game_id,
        team_id,
        player_id,
        car_id,
        color as team_color,
        core_shots::integer as shots,
        core_goals::integer as goals,
        core_saves::integer as saves,
        core_assists::integer as assists,
        core_score::integer as player_score,
        core_shooting_percentage,
        ADVANCED_GOAL_PARTICIPATION,
        boost_bpm::integer as boost_bpm,
        boost_bcpm::integer as boost_bcpm,
        boost_avg_amount::integer as boost_avg_amount,
        boost_amount_collected::integer as boost_amount_collected,
        boost_amount_stolen::integer as boost_amount_stolen,
        boost_amount_collected_big::integer as boost_amount_collected_big,
        boost_amount_stolen_big::integer as boost_amount_stolen_big,
        boost_amount_collected_small::integer as boost_amount_collected_small,
        boost_amount_stolen_small::integer as boost_amount_stolen_small,
        boost_count_collected_big::integer as boost_count_collected_big,
        boost_count_stolen_big::integer as boost_count_stolen_big,
        boost_count_collected_small::integer as boost_count_collected_small,
        boost_count_stolen_small::integer as boost_count_stolen_small,
        boost_amount_overfill::integer as boost_amount_overfill,
        boost_amount_overfill_stolen::integer as boost_amount_overfill_stolen,
        boost_amount_used_while_supersonic::integer as boost_amount_used_while_supersonic,
        boost_time_zero_boost::integer as boost_time_zero_boost,
        boost_percent_zero_boost::integer as boost_percent_zero_boost,
        boost_time_full_boost::integer as boost_time_full_boost,
        boost_percent_full_boost::integer as boost_percent_full_boost,
        boost_time_boost_0_25::integer as boost_time_boost_0_25,
        boost_time_boost_25_50::integer as boost_time_boost_25_50,
        boost_time_boost_50_75::integer as boost_time_boost_50_75,
        boost_time_boost_75_100::integer as boost_time_boost_75_100,
        boost_percent_boost_0_25::integer as boost_percent_boost_0_25,
        boost_percent_boost_25_50::integer as boost_percent_boost_25_50,
        boost_percent_boost_50_75::integer as boost_percent_boost_50_75,
        boost_percent_boost_75_100::integer as boost_percent_boost_75_100,
        movement_avg_speed::integer as movement_avg_speed,
        movement_total_distance::integer as movement_total_distance,
        movement_time_supersonic_speed::integer as movement_time_supersonic_speed,
        movement_time_boost_speed::integer as movement_time_boost_speed,
        movement_time_slow_speed::integer as movement_time_slow_speed,
        movement_time_ground::integer as movement_time_ground,
        movement_time_low_air::integer as movement_time_low_air,
        movement_time_high_air::integer as movement_time_high_air,
        movement_time_powerslide::integer as movement_time_powerslide,
        movement_count_powerslide::integer as movement_count_powerslide,
        movement_avg_powerslide_duration::integer as movement_avg_powerslide_duration,
        movement_avg_speed_percentage::integer as movement_avg_speed_percentage,
        movement_percent_slow_speed::integer as movement_percent_slow_speed,
        movement_percent_boost_speed::integer as movement_percent_boost_speed,
        movement_percent_supersonic_speed::integer as movement_percent_supersonic_speed,
        movement_percent_ground::integer as movement_percent_ground,
        movement_percent_low_air::integer as movement_percent_low_air,
        movement_percent_high_air::integer as movement_percent_high_air,
        positioning_avg_distance_to_ball::integer as positioning_avg_distance_to_ball,
        positioning_avg_distance_to_ball_possession::integer as positioning_avg_distance_to_ball_possession,
        positioning_avg_distance_to_ball_no_possession::integer as positioning_avg_distance_to_ball_no_possession,
        positioning_avg_distance_to_mates::integer as positioning_avg_distance_to_mates,
        positioning_time_defensive_third::integer as positioning_time_defensive_third,
        positioning_time_neutral_third::integer as positioning_time_neutral_third,
        positioning_time_offensive_third::integer as positioning_time_offensive_third,
        positioning_time_defensive_half::integer as positioning_time_defensive_half,
        positioning_time_offensive_half::integer as positioning_time_offensive_half,
        positioning_time_behind_ball::integer as positioning_time_behind_ball,
        positioning_time_in_front_ball::integer as positioning_time_in_front_ball,
        positioning_time_most_back::integer as positioning_time_most_back,
        positioning_time_most_forward::integer as positioning_time_most_forward,
        positioning_goals_against_while_last_defender::integer as positioning_goals_against_while_last_defender,
        positioning_time_closest_to_ball::integer as positioning_time_closest_to_ball,
        positioning_time_farthest_from_ball::integer as positioning_time_farthest_from_ball,
        positioning_percent_defensive_third::integer as positioning_percent_defensive_third,
        positioning_percent_offensive_third::integer as positioning_percent_offensive_third,
        positioning_percent_neutral_third::integer as positioning_percent_neutral_third,
        positioning_percent_defensive_half::integer as positioning_percent_defensive_half,
        positioning_percent_offensive_half::integer as positioning_percent_offensive_half,
        positioning_percent_behind_ball::integer as positioning_percent_behind_ball,
        positioning_percent_in_front_ball::integer as positioning_percent_in_front_ball,
        positioning_percent_most_back::integer as positioning_percent_most_back,
        positioning_percent_most_forward::integer as positioning_percent_most_forward,
        positioning_percent_closest_to_ball::integer as positioning_percent_closest_to_ball,
        positioning_percent_farthest_from_ball::integer as positioning_percent_farthest_from_ball,
        advanced_rating,
        demo_inflicted::integer as demo_inflicted,
        demo_taken::integer as demo_taken,
        winner::text as winner
    from player_games
)

select * from players